// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace repodesktopweb_backend.Models;

public partial class Folder
{
    public int Id { get; set; }

    public string NameFolder { get; set; }

    public string Descripcion { get; set; }

    public string ColorFolder { get; set; }

    public int PositionFolder { get; set; }

    public DateTime Fecrea { get; set; }

    public int? Iduser { get; set; }

    public int? Estado { get; set; }

    public int? Permisos { get; set; }

    public string Password { get; set; }
}