// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace repodesktopweb_backend.Models;

public partial class Membresia
{
    public int Id { get; set; }

    public string NombrePaquete { get; set; }

    public int? DuracionDias { get; set; }

    public decimal? Costo { get; set; }

    public decimal? Descuento { get; set; }

    public DateTime Fecrea { get; set; }

    public int? Estado { get; set; }
}